//create user
POST http://localhost:5000/users 
Content-Type: application/json

{
    "name": "tess",
    "email": "tes@gmail.com",
    "password": "12345678",
    "confPassword": "12345678",
    "role": "user"
}

###
//get all users
GET http://localhost:5000/users

###
//get user by id
Get http://localhost:5000/users/10ca793f-52ee-44a8-b60b-789eb83a418f

###
//update user
PATCH  http://localhost:5000/users/2f7a4015-b1fa-402b-b501-6445798fcf19
Content-Type: application/json

{
    "name": "tes123 ",
    "email": "tesss@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
//delete user
DELETE http://localhost:5000/users/2f7a4015-b1fa-402b-b501-6445798fcf19

###
//Post product
POST http://localhost:5000/product
Content-Type: application/json

{
    "name": "tes6",
    "price": "234"
}